# Generated by Django 3.1 on 2020-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200923_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Block',
            new_name='PermanentBlock',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='City',
            new_name='PermanentCity',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='District',
            new_name='PermanentDistrict',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Pin',
            new_name='PermanentPin',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='State',
            new_name='PermanentState',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Village',
            new_name='PermanentVillage',
        ),
        migrations.AddField(
            model_name='customer',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='RessidentialBlock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='RessidentialCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='RessidentialDistrict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='RessidentialPin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='RessidentialState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='RessidentialVillage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
