# Generated by Django 3.1 on 2020-09-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200924_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='BankAccount',
        ),
        migrations.RemoveField(
            model_name='official_address',
            name='District',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='BankAccountNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
