# Generated by Django 3.1 on 2020-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200925_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='KOID_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
